CREATE TABLE "reactions" (
	"id" serial PRIMARY KEY NOT NULL,
	"symbol" text NOT NULL,
	"timeframe" text NOT NULL,
	"zone_type" text,
	"zone_bottom" numeric,
	"zone_top" numeric,
	"approach" text,
	"tapped_edge" text,
	"direction" text,
	"formed_at" timestamp with time zone,
	"tapped_at" timestamp with time zone,
	"outcome" text,
	"entry_price" numeric,
	"mfe_pct" numeric,
	"mae_pct" numeric,
	"move_pts" numeric,
	"move_pct" numeric,
	"bars_to_peak" integer,
	"atr_expansion" numeric,
	"vol_expansion" numeric,
	"pattern" text,
	"fingerprint" jsonb,
	"source" text DEFAULT 'backfill' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
